executable: "planet.exe"
arguments:
  - "-s": "0.2000000"
  - "-i": "-0.042"
  - "-w": "1024"
  - "-h": "512"
  - "-o": "\"{output_file}\""
  - "-m": "1"
  - "-p": "q"
  - "-C": "olssonlight.col"
  - "-V": "-0.069"
  - "-v": "-0.3721"
  - "-M": "0.1"
  - "-l": "70.0"
  - "-L": "0.0"
input_redirection: "< \"{sketch_file}\""
